import { wechatCloudStorageRepository } from '../repositories/wechatCloudStorageRepository.js';
import { syncService } from './syncService.js';

export const cloudStorageService = {
  async prepareImageUpload(itemId, imageRevision, extension) {
    if (typeof wx === 'undefined' || !wx.cloud) {
      throw new Error('wx.cloud not available');
    }
    const res = await wx.cloud.callFunction({
      name: 'imageProcess',
      data: {
        action: 'prepareUpload',
        itemId,
        imageRevision,
        extension
      }
    });
    const result = res.result || {};
    if (!result.success) {
      throw new Error(result.errorMessage || 'Failed to prepare upload');
    }
    return result; // returns { jobId, uploadTicket, cloudPath }
  },

  async uploadOriginalImage(localPath, cloudPath) {
    return await wechatCloudStorageRepository.uploadFile(localPath, cloudPath);
  },

  async processImage(jobId, uploadTicket, itemId, imageRevision, originalCloudFileId) {
    if (typeof wx === 'undefined' || !wx.cloud) {
      throw new Error('wx.cloud not available');
    }
    const res = await wx.cloud.callFunction({
      name: 'imageProcess',
      data: {
        action: 'processUpload',
        jobId,
        uploadTicket,
        itemId,
        imageRevision,
        originalCloudFileId
      }
    });
    const result = res.result || {};
    if (!result.success) {
      throw new Error(result.errorMessage || 'Failed to process image');
    }
    return result; // returns { imageProcessStatus, cutoutCloudFileId, errorCode }
  },
  
  async resolveImageUrl(fileId) {
    if (!fileId) return '';
    if (!fileId.startsWith('cloud://')) return fileId;
    try {
      const res = await wechatCloudStorageRepository.getTempFileURL([fileId]);
      if (res && res.length > 0 && res[0].tempFileURL) {
        return res[0].tempFileURL;
      }
    } catch (e) {
      console.error('Failed to resolve image URL', e);
    }
    return fileId;
  },

  async executeBackgroundUpload(itemService, itemId, imageRevision, originalLocalPath, displayLocalPath, localExt, userConsentAccepted, syncEnabled) {
    const isSyncActive = syncEnabled !== undefined ? syncEnabled : syncService.getSettings().syncEnabled;
    if (!isSyncActive) {
      // Sync is disabled, we do nothing and keep local image
      itemService.updateItemImageState(itemId, imageRevision, {
        imageProcessStatus: 'fallback',
        beautifyFallbackReason: 'sync_disabled',
        imageSyncPending: true
      });
      return;
    }

    try {
      itemService.updateItemImageState(itemId, imageRevision, { imageProcessStatus: 'uploading' });

      const prepareRes = await this.prepareImageUpload(itemId, imageRevision, localExt);
      const { cloudPath } = prepareRes;

      const originalCloudFileId = await this.uploadOriginalImage(originalLocalPath, cloudPath);

      if (!userConsentAccepted || originalLocalPath === displayLocalPath) {
        // Only upload original, skip processing
        itemService.updateItemImageState(itemId, imageRevision, {
          originalImageCloudFileId: originalCloudFileId,
          displayImageCloudFileId: originalCloudFileId,
          imageProcessStatus: 'fallback',
          beautifyFallbackReason: 'user_declined',
          imageSyncPending: false
        });
        
        uni.showToast({ title: '图片备份完成', icon: 'success' })
        return;
      }

      itemService.updateItemImageState(itemId, imageRevision, {
        originalImageCloudFileId: originalCloudFileId,
        imageProcessStatus: 'cutting'
      });

      // Upload display sticker directly since it's already generated by frontend canvas
      const stickerExt = displayLocalPath.match(/\.([a-zA-Z0-9]+)$/) ? displayLocalPath.match(/\.([a-zA-Z0-9]+)$/)[1] : 'png';
      const prepareRes2 = await this.prepareImageUpload(itemId + '_sticker', imageRevision, stickerExt);
      const displayImageCloudFileId = await this.uploadOriginalImage(displayLocalPath, prepareRes2.cloudPath);

      itemService.updateItemImageState(itemId, imageRevision, {
        originalImageCloudFileId: originalCloudFileId,
        displayImageCloudFileId,
        imageProcessStatus: 'success',
        imageSyncPending: false
      });

      uni.showToast({ title: '贴纸上云完成', icon: 'success' })
    } catch (e) {
      console.error('Background upload error', e);
      itemService.updateItemImageState(itemId, imageRevision, {
        imageProcessStatus: 'error',
        imageSyncPending: true
      });
      uni.showToast({ title: '图片上云失败', icon: 'none' })
    }
  }
};
